apiVersion: v1
kind: Secret
metadata:
  name: todo-app-secrets
  namespace: todo-app
type: Opaque
data:
  # Base64 encoded values
  # echo -n "your_mysql_password" | base64
  db-password: cGFzc3dvcmQ=
  # echo -n "your_jwt_secret_key" | base64
  jwt-secret: bXlTZWNyZXRLZXk=